CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY NOT NULL,
  ggg_account_name VARCHAR(255) NOT NULL,
  oauth_access_token TEXT NOT NULL,
  oauth_refresh_token TEXT NOT NULL,
  oauth_expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS characters (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  user_id TEXT NOT NULL,
  realm VARCHAR(255) NOT NULL,
  class VARCHAR(255) NOT NULL,
  league VARCHAR(255) NOT NULL,
  level INT NOT NULL,
  experience BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
